with-expecter: true
issue-845-fix: true
resolve-type-alias: false
dir: mocks
outPkg: mocks
packages:
  github.com/restatedev/sdk-go/internal/state:
    interfaces:
      # these have been manually edited. If you want to regenerate, uncomment here,
      # generate, and then make sure the previous diffs are carried over!
      # AfterFuture:
      # AwakeableFuture:
      # Client:
      # Context:
      # DurablePromise:
      # ResponseFuture
      Rand:
      Selector:
  github.com/restatedev/sdk-go/internal/rand:
    interfaces:
      Rand:
