with-expecter: true
issue-845-fix: true
resolve-type-alias: false
dir: mocks
outPkg: mocks
packages:
  github.com/restatedev/sdk-go/internal/restatecontext:
    interfaces:
      AfterFuture:
      AttachFuture:
      AwakeableFuture:
      Client:
      Context:
      DurablePromise:
      Invocation:
      ResponseFuture:
      RunAsyncFuture:
      Selector:
  github.com/restatedev/sdk-go/internal/rand:
    interfaces:
      Rand:
