package restatecontext

import (
	"context"
	"io"
	"log/slog"
	rand2 "math/rand/v2"
	"sync/atomic"
	"time"

	"github.com/google/uuid"
	"github.com/restatedev/sdk-go/internal/errors"
	pbinternal "github.com/restatedev/sdk-go/internal/generated"
	"github.com/restatedev/sdk-go/internal/log"
	"github.com/restatedev/sdk-go/internal/options"
	"github.com/restatedev/sdk-go/internal/randsource"
	"github.com/restatedev/sdk-go/internal/statemachine"
	"github.com/restatedev/sdk-go/internal/stringmap"
	"github.com/restatedev/sdk-go/logging"
)

type Request struct {
	// The unique id that identifies the current function invocation. This id is guaranteed to be
	// unique across invocations, but constant across reties and suspensions.
	ID string
	// Scope is the invocation scope supplied by the runtime.
	Scope string
	// LimitKey is the invocation concurrency limit key supplied by the runtime.
	LimitKey string
	// IdempotencyKey is the idempotency key supplied by the runtime.
	IdempotencyKey string
	// Request headers - the following headers capture the original invocation headers, as provided to
	// the ingress.
	Headers stringmap.Map
	// Attempt headers - the following headers are sent by the restate runtime.
	// These headers are attempt specific, generated by the restate runtime uniquely for each attempt.
	// These headers might contain information such as the W3C trace context, and attempt specific information.
	AttemptHeaders map[string][]string
	// Raw unparsed request body
	Body []byte
}

type Context interface {
	context.Context
	Log() *slog.Logger
	Request() *Request
	Wrap(wrappedCtx context.Context) Context

	// available outside of .Run()
	RandInstance() *rand2.Rand
	RandUUID() uuid.UUID
	RandSource() rand2.Source
	Sleep(d time.Duration, opts ...options.SleepOption) errors.TerminalError
	After(d time.Duration, opts ...options.SleepOption) AfterFuture
	Service(service, method string, options ...options.ClientOption) Client
	Object(service, key, method string, options ...options.ClientOption) Client
	Workflow(seservice, workflowID, method string, options ...options.ClientOption) Client
	CancelInvocation(invocationId string)
	AttachInvocation(invocationId string, opts ...options.AttachOption) AttachFuture
	Awakeable(options ...options.AwakeableOption) AwakeableFuture
	ResolveAwakeable(id string, value any, options ...options.ResolveAwakeableOption)
	RejectAwakeable(id string, reason error)
	Signal(name string, options ...options.SignalOption) SignalFuture
	ResolveSignal(invocationID string, name string, value any, options ...options.ResolveSignalOption)
	RejectSignal(invocationID string, name string, reason error)
	WaitIter(futs ...Future) WaitIterator
	Run(fn func(ctx RunContext) (any, error), output any, options ...options.RunOption) errors.TerminalError
	RunAsync(fn func(ctx RunContext) (any, error), options ...options.RunOption) RunAsyncFuture

	// available on all keyed handlers
	Get(key string, output any, options ...options.GetOption) (bool, errors.TerminalError)
	Keys() ([]string, errors.TerminalError)
	Key() string

	// available on non-shared keyed handlers
	Set(key string, value any, options ...options.SetOption)
	Clear(key string)
	ClearAll()

	// available on workflow handlers
	Promise(name string, options ...options.PromiseOption) DurablePromise
}

type ctx struct {
	context.Context

	// stream does not implement `Close`
	// because the handler makes sure to drain
	// and close the request stream at the end
	// before the requestHandler returns.
	stream   io.ReadWriter
	readChan chan readResult

	stateMachine *statemachine.StateMachine

	// Info about the invocation
	key          string
	request      Request
	isProcessing bool

	// Logging
	userLogContext atomic.Pointer[logging.LogContext]
	internalLogger *slog.Logger
	userLogger     *slog.Logger

	// Random
	rand               *rand2.Rand
	templateRandSource *randsource.Source

	// Run implementation
	runClosures           map[uint32]func() *pbinternal.VmProposeRunCompletionParameters
	runClosureCompletions chan *pbinternal.VmProposeRunCompletionParameters
}

var _ Context = (*ctx)(nil)

func newContext(inner context.Context, machine *statemachine.StateMachine, invocationInput *pbinternal.VmSysInputReturn_Input, stream io.ReadWriter, attemptHeaders map[string][]string, dropReplayLogs bool, logHandler slog.Handler) *ctx {
	headers := make(map[string]string)
	for _, h := range invocationInput.GetHeaders() {
		headers[h.GetKey()] = h.GetValue()
	}
	request := Request{
		ID:             invocationInput.GetInvocationId(),
		Scope:          invocationInput.GetScope(),
		LimitKey:       invocationInput.GetLimitKey(),
		IdempotencyKey: invocationInput.GetIdempotencyKey(),
		Headers:        stringmap.New(headers),
		AttemptHeaders: attemptHeaders,
		Body:           invocationInput.GetInput(),
	}

	logHandler = logHandler.WithAttrs([]slog.Attr{slog.String("invocationID", invocationInput.GetInvocationId())})
	internalLogger := slog.New(log.NewRestateContextHandler(logHandler))
	inner = statemachine.WithLogger(inner, internalLogger)

	var templateRandSource *randsource.Source
	if invocationInput.GetShouldUseRandomSeed() {
		templateRandSource = randsource.NewFromSeed(invocationInput.GetRandomSeed())
	} else {
		templateRandSource = randsource.NewFromInvocationId([]byte(invocationInput.GetInvocationId()))
	}

	// will be cancelled when the http2 stream is cancelled
	// but NOT when we just doSuspend - just because we can't get completions doesn't mean we can't make
	// progress towards producing an output message
	ctx := &ctx{
		Context:               inner,
		stream:                stream,
		readChan:              make(chan readResult),
		stateMachine:          machine,
		key:                   invocationInput.GetKey(),
		request:               request,
		internalLogger:        internalLogger,
		userLogContext:        atomic.Pointer[logging.LogContext]{},
		rand:                  rand2.New(templateRandSource.Copy()),
		templateRandSource:    templateRandSource,
		userLogger:            nil,
		isProcessing:          false,
		runClosures:           make(map[uint32]func() *pbinternal.VmProposeRunCompletionParameters),
		runClosureCompletions: make(chan *pbinternal.VmProposeRunCompletionParameters, 10),
	}
	ctx.userLogger = slog.New(log.NewUserContextHandler(&ctx.userLogContext, dropReplayLogs, logHandler))

	// Prepare logger
	ctx.userLogContext.Store(&logging.LogContext{Source: logging.LogSourceUser, IsReplaying: true})

	// It might be we're already in processing phase
	ctx.checkStateTransition()

	return ctx
}

func (restateCtx *ctx) Log() *slog.Logger {
	return restateCtx.userLogger
}

func (restateCtx *ctx) Request() *Request {
	return &restateCtx.request
}

func (restateCtx *ctx) RandInstance() *rand2.Rand {
	return restateCtx.rand
}

func (restateCtx *ctx) RandUUID() uuid.UUID {
	return randsource.UUIDFromRand(restateCtx.rand)
}

func (restateCtx *ctx) RandSource() rand2.Source {
	return restateCtx.templateRandSource
}

func (restateCtx *ctx) Key() string {
	return restateCtx.key
}

func (restateCtx *ctx) Wrap(wrapped context.Context) Context {
	return &restateCtxWithWrappedContext{
		restateCtx,
		wrapped,
	}
}

func (restateCtx *ctx) checkStateTransition() {
	if restateCtx.isProcessing {
		return
	}
	// Check if we transitioned to processing
	processing, err := restateCtx.stateMachine.IsProcessing(restateCtx)
	if err != nil {
		panic(err)
	}
	if processing {
		restateCtx.userLogContext.Store(&logging.LogContext{Source: logging.LogSourceUser, IsReplaying: false})
		restateCtx.isProcessing = true
	}
}

type restateCtxWithWrappedContext struct {
	*ctx
	wrapped context.Context
}

func (restateCtx *restateCtxWithWrappedContext) Run(fn func(ctx RunContext) (any, error), output any, opts ...options.RunOption) errors.TerminalError {
	return restateCtx.runAsync(restateCtx, fn, opts...).Result(output)
}

func (restateCtx *restateCtxWithWrappedContext) RunAsync(fn func(ctx RunContext) (any, error), opts ...options.RunOption) RunAsyncFuture {
	return restateCtx.runAsync(restateCtx, fn, opts...)
}

func (restateCtx *restateCtxWithWrappedContext) Value(key interface{}) interface{} {
	if value := restateCtx.wrapped.Value(key); value != nil {
		return value
	}
	return restateCtx.ctx.Value(key)
}

var _ Context = (*restateCtxWithWrappedContext)(nil)
