// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

/* moved to helpers.go
// MockRunAsyncFuture is an autogenerated mock type for the RunAsyncFuture type
type MockRunAsyncFuture struct {
	mock.Mock
}
*/

type MockRunAsyncFuture_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunAsyncFuture) EXPECT() *MockRunAsyncFuture_Expecter {
	return &MockRunAsyncFuture_Expecter{mock: &_m.Mock}
}

// Result provides a mock function with given fields: output
func (_m *MockRunAsyncFuture) Result(output any) error {
	ret := _m.Called(output)

	if len(ret) == 0 {
		panic("no return value specified for Result")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any) error); ok {
		r0 = rf(output)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRunAsyncFuture_Result_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Result'
type MockRunAsyncFuture_Result_Call struct {
	*mock.Call
}

// Result is a helper method to define mock.On call
//   - output any
func (_e *MockRunAsyncFuture_Expecter) Result(output interface{}) *MockRunAsyncFuture_Result_Call {
	return &MockRunAsyncFuture_Result_Call{Call: _e.mock.On("Result", output)}
}

func (_c *MockRunAsyncFuture_Result_Call) Run(run func(output any)) *MockRunAsyncFuture_Result_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *MockRunAsyncFuture_Result_Call) Return(_a0 error) *MockRunAsyncFuture_Result_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRunAsyncFuture_Result_Call) RunAndReturn(run func(any) error) *MockRunAsyncFuture_Result_Call {
	_c.Call.Return(run)
	return _c
}

// handle provides a mock function with no fields
func (_m *MockRunAsyncFuture) handle() uint32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for handle")
	}

	var r0 uint32
	if rf, ok := ret.Get(0).(func() uint32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint32)
	}

	return r0
}

// MockRunAsyncFuture_handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'handle'
type MockRunAsyncFuture_handle_Call struct {
	*mock.Call
}

// handle is a helper method to define mock.On call
func (_e *MockRunAsyncFuture_Expecter) handle() *MockRunAsyncFuture_handle_Call {
	return &MockRunAsyncFuture_handle_Call{Call: _e.mock.On("handle")}
}

func (_c *MockRunAsyncFuture_handle_Call) Run(run func()) *MockRunAsyncFuture_handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRunAsyncFuture_handle_Call) Return(_a0 uint32) *MockRunAsyncFuture_handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRunAsyncFuture_handle_Call) RunAndReturn(run func() uint32) *MockRunAsyncFuture_handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRunAsyncFuture creates a new instance of MockRunAsyncFuture. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunAsyncFuture(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunAsyncFuture {
	mock := &MockRunAsyncFuture{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
