#!/usr/bin/env bash
#
# Regenerates the testify mocks in x/mocks/ from the interfaces listed in
# .mockery.yaml, then re-applies the hand-maintained tweaks the hybrid setup needs.
#
# Why the post-processing: mockery emits a full `type MockX struct { mock.Mock }`
# plus a constructor for every interface. But:
#   * The future mocks (ResponseFuture, AwakeableFuture, ...) must EMBED
#     restatecontext.Future to satisfy its unexported handle() method (a mock
#     in package `mocks` cannot implement an unexported method from another
#     package). Those structs are therefore hand-written in x/mocks/helpers.go,
#     so we delete the generated struct defs that would collide with them.
#   * MockContext / MockClient use richer hand-written constructors in
#     helpers.go (they wire up t via setT), so we delete the generated ones.
#
# Each block we delete starts at a unique comment line and ends at the next
# line that is just "}", so a sed range delete removes it exactly.
#
# Run this from anywhere; it operates on the repo root.
set -euo pipefail
cd "$(dirname "$0")/.."

if ! command -v mockery >/dev/null 2>&1; then
	echo "error: mockery not found on PATH (install github.com/vektra/mockery/v2@v2.52.2)" >&2
	exit 1
fi

( cd x/mocks && mockery )

# Future mocks embed restatecontext.Future (struct lives in helpers.go): drop the generated struct defs.
for iface in ResponseFuture RunAsyncFuture AttachFuture AwakeableFuture DurablePromise AfterFuture; do
	sed -i "/^\/\/ Mock${iface} is an autogenerated mock type/,/^}$/d" "x/mocks/mock_${iface}.go"
done

# MockContext / MockClient constructors are hand-written in helpers.go: drop the generated ones.
sed -i '/^\/\/ NewMockContext creates/,/^}$/d' x/mocks/mock_Context.go
sed -i '/^\/\/ NewMockClient creates/,/^}$/d' x/mocks/mock_Client.go

# Tidy up the blank lines left behind, then make sure it still builds.
gofmt -w x/mocks/
( cd x/mocks && go build ./... )

echo "mocks regenerated and reconciled in x/mocks/"
