name: Go
on: [push]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: warp-ubuntu-latest-x64-4x

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: go get .
      - name: Vet
        run: go vet -v ./...
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v ./...
      - name: Check dependency licenses
        run: |
          go install github.com/google/go-licenses@v1.6.0
          go-licenses check ./... --allowed_licenses=Apache-2.0,MIT,BSD-2-Clause,BSD-3-Clause,ISC,0BSD,MPL-2.0
